{
  "openapi": "3.0.1",
  "info": {
    "title": "API RDV insertion",
    "version": "v1",
    "description": "L'API de RDV-Solidarités vous permet de lire des données dans notre base depuis votre logiciel.\n\nToutes les fonctionnalités de RDV-Solidarités ne sont pas encore disponibles via l’API. Contactez-nous si vous avez besoin de fonctionnalités qui ne sont pas encore présentes.\n\n# Requêtes\n\nL'API adhère aux principes REST :\n\n- requêtes `GET` : lecture sans modification\n- requêtes `POST` : création de nouvelle ressource\n- requêtes `PATCH` : mise à jour d'une ressource existante\n- requêtes `DELETE` : suppression d'une ressource\n\nLes paramètres des requêtes `GET` doivent être envoyés via les query string de la requête.\n\nLes paramètres des requêtes `POST` doivent être transmis dans le corps de la requête sous un format JSON valide, et doivent contenir le header `Content-Type: application/json`.\n\nLes paramètres doivent respecter les formats suivants :\n\n- `DATE` : \"YYYY-MM-DD\" par exemple : \"2021-10-21\"\n- `TIME` : H:m[:s], par exemple : \"10:30\"\n\n# Versionnage\n\nL'API est versionnée. La version actuelle est 1.0 (référencée comme v1 dans les points de terminaison).\n\n# Routes\n\nLes points de terminaison de l'API sont accessibles par une route de la forme : `https://<domain>/api/<version>/<endpoint>`.\n\nAvec :\n\n- `version` est la version de l'API\n- `endpoint` est le nom du point de terminaison\n\nPar exemple, on aura : `https://<domain>/api/v1/absences`\n\nPour la version production, les requêtes doivent être adressées à https://www.rdv-solidarites.fr et non à https://rdv-solidarites.fr.\n\nPour la version démo, les requêtes doivent être adressées à https://demo.rdv-solidarites.fr.\n\n# Authentification\n\nCertains points de terminaison sont réservés aux agents authentifiés, dans la limite de leur rôle au sein de l'application.\n\n## Headers d'authentification\n\nTous les agents peuvent utiliser l'API. Les requêtes faites sur l'API sont authentifiées grace à des tokens d'accès associés à chaque agent. Chaque action faite via l'API est donc attribuable à un agent.\n\nPour récupérer le token d'accès d'un agent il faut faire une première requête `POST` à l'url `https://www.rdv-solidarites.fr/api/v1/auth/sign_in` en passant en paramètres JSON l'email et le mot de passe de l'agent. Par exemple (avec HTTPie) :\n\n```httpie\nhttp --json POST 'https://www.rdv-solidarites.fr/api/v1/auth/sign_in' \\\n  email='martine@demo.rdv-solidarites.fr' password='123456'\n```\n\nEn cas de succès d'authentification, la réponse à cette requête contiendra dans le corps le détail de l'agent, et dans les headers les token d'accès à l'API. Par exemple :\n\n```http\nHTTP/1.1 200 OK\nX-Frame-Options: SAMEORIGIN\nX-XSS-Protection: 1; mode=block\nX-Content-Type-Options: nosniff\nX-Download-Options: noopen\nX-Permitted-Cross-Domain-Policies: none\nReferrer-Policy: strict-origin-when-cross-origin\nContent-Type: application/json; charset=utf-8\naccess-token: SFYBngO55ImjD1HOcv-ivQ< token-type: Bearer\nclient: Z6EihQAY9NWsZByfZ47i_Q< expiry: 1605600758\nuid: martine@demo.rdv-solidarites.fr\nETag: W/\"0fe52663d6745c922160384e13afe1e1\"\nCache-Control: max-age=0, private, must-revalidate\nX-Meta-Request-Version: 0.7.2\nX-Request-Id: 291fab6a-043b-4b9c-b4b9-3c7fc9c9453a\nX-Runtime: 0.194743< Transfer-Encoding: chunked\n* Connection #0 to host rdv-solidarites.fr left intact\n{\n  \"data\": {\n    \"id\":1,\n    \"deleted_at\":null,\n    \"email\":\"martine@demo.rdv-solidarites.fr\",\n    \"provider\":\"email\",\n    \"service_id\":1,\n    \"role\":\"admin\",\n    \"last_name\":\"VALIDAY\",\n    \"first_name\":\"Martine\",\n    \"uid\":\"martine@demo.rdv-solidarites.fr\",\n    \"email_original\":null,\n    \"allow_password_change\":false\n  }\n}\n* Closing connection 0\n```\n\nLes 3 headers essentiels pour l'authentification sont les suivants :\n\n```http\naccess-token: SFYBngO55ImjD1HOcv-ivQ\nclient: Z6EihQAY9NWsZByfZ47i_Q\nuid: martine@demo.rdv-solidarites.fr\n```\n\n- `access-token` : c'est le jeton d'accès qui vous a été attribué. Il a une durée de vie de 24h, après ça il vous faudra reproduire cette procédure pour en récupérer un nouveau.\n- `client` : un identifiant unique associé à l'appareil depuis lequel vous avez effectué la requête\n- `uid` : l'identifiant de l'agent dans l'API, égal à l'email de l'agent.\n\n**Ces 3 headers doivent être transmis avec chacune de vos requêtes successives à l'API**, peu importe la méthode HTTP.\n\n## Permissions\n\nLes rôles et permissions des agents sont les mêmes via l'API que depuis l'interface web.\n\nC'est à dire que les agents classiques ont accès à leur service uniquement, les agents du service secrétariat peuvent accéder aux agendas des agents des autres services, les agents admin ont accès à toute l'organisation, etc.\n\nPar défaut, les requêtes en lecture n'appliquent aucun filtre et retourneront toutes les ressources auxquelles a accès l'agent connecté. Par exemple si un agent admin fait une requête pour accéder à la liste des absences sans filtre, l'API retournera toutes les absences de tous les agents appartenant aux organisations dont fait partie cet agent admin, ce qui peut faire beaucoup.\n\n# Sérialisation\n\nL'API supporte uniquement le format JSON. Toutes les réponses envoyées par l'API contiendront le header `Content-Type: application/json` et leur contenu est présent dans le body dans un format JSON à désérialiser.\n\n# Pagination des réponses par listes\n\nTous les points de terminaison qui retournent des listes sont paginés. De manière générale, tout point de terminaison qui retourne une liste peut retourner une liste vide.\n\n## Paramètres\n\nLe paramètre (optionnel) `page` permet d'accéder à une page donnée. Sauf précision contraire dans la documentation d'un point de terminaison donné, on retrouve 100 éléments par page.\n\n## Résultats\n\nLa réponse contient en outre un objet meta qui indique le nombre total de pages et d’items, par exemple :\n\n```rb\n{\n  […],\n  \"meta\": {\n      \"current_page\": 1,\n      \"total_count\": 112,\n      \"total_pages\": 2\n  }\n}\n```\n\n# Rate limiting\n\nL'utilisation de l'API est limitée pour les points de terminaison sans authentification. Vous pouvez effectuer au maximum 50 appels par minutes. Si vous dépassez cette limite, une erreur 429 vous sera renvoyée et vous trouverez le temps que vous devez attendre avant de relancer une requête dans le header (`Retry-After`).\n\n# Codes de retour\n\nL'API est susceptible de retourner les codes suivants :\n\n| Code  | Nom                   | Description                                                                   |\n| ----- | --------------------- | ----------------------------------------------------------------------------- |\n| `200` | Success               | Succès                                                                        |\n| `204` | No Content            | Succès mais la réponse ne contient pas de données (exemple : suppression)     |\n| `400` | Bad Request           | La requête est invalide                                                       |\n| `401` | Unauthorized          | L'authentification a échoué                                                   |\n| `403` | Forbidden             | Droits insuffisants pour réaliser l'action demandée                           |\n| `404` | Not Found             | La ressource est introuvable                                                  |\n| `422` | Unprocessable Entity  | La donnée transmise est mal formattée                                         |\n| `429` | Too Many Requests     | Trop de requêtes ont été effectuées                                           |\n| `500` | Internal Server Error | Une erreur serveur produite (l'équipe technique est notifiée automatiquement) |\n\n# Erreurs\n\nEn cas d'erreur reconnue par le système (par exemple erreur 422), les champs suivants seront présents dans la réponse pour vous informer sur les problèmes :\n\n- `errors` : [ERREUR] : liste d'erreurs groupées par attribut problèmatique au format machine\n- `error_messages` : [ERREUR] : idem mais dans un format plus facilement lisible.\n\n# Principes fonctionnels\n\n- Les statuts des RDV et des participants.\n\nLe statut du RDV (status) est un statut général. **Il n'est pas représentatif des statuts individuels des usagers.**\n\n**Chaque participant au RDV a son propre statut de participation porté par l'association `rdvs_users` du RDV.**\n\nPour les RDV avec l'attribut collectif à false les statuts du/des participants et du RDV seront tous identiques. (dans l'exemple suivant : `seen`)\n\nIl est conseillé malgrés tout d'utiliser les statuts des participants (dans `rdvs_users`) quelque soit le type de rdv.\n\n```rb\n{\n  \"rdvs\": [\n    {\n      \"id\": 8,\n      \"collectif\": false,\n      \"status\": \"seen\",\n      \"rdvs_users\": [\n        {\n          \"id\": 8,\n          \"status\": \"seen\",\n          \"user\": {\n            \"id\": 10,\n            \"first_name\": \"Tristan\",\n            \"last_name\": \"LEROUX\",\n          }\n        },\n        {\n          \"id\": 9,\n          \"status\": \"seen\",\n          \"user\": {\n            \"id\": 11,\n            \"first_name\": \"Marie\",\n            \"last_name\": \"LEROUX\",\n          }\n        }\n      ],\n      \"users_count\": 2,\n    }\n  ],\n}\n```\n\nPour les RDV avec l'attribut collectif à true les statuts du/des participants peuvent être différents.\n\nIci, le RDV a un status `seen` mais les 3 participants ont des status de participation différents.\n\n- Tristan Leroux s'est présenté au RDV collectif : `seen`\n- Roger Lapin ne s'est pas présenté et n'a pas annulé : `noshow`\n- Marie Dupont a annulé sa venue : `excused`\n\n`users_count` représente le nombre d'inscrits au RDV en temps réél (Tous les statuts hors `revoked` et `excused`)\n\n```rb\n{\n  \"rdvs\": [\n    {\n      \"id\": 8,\n      \"collectif\": true,\n      \"status\": \"seen\",\n      \"rdvs_users\": [\n        {\n          \"id\": 8,\n          \"status\": \"seen\",\n          \"user\": {\n            \"id\": 10,\n            \"first_name\": \"Tristan\",\n            \"last_name\": \"LEROUX\",\n          }\n        },\n        {\n          \"id\": 9,\n          \"status\": \"noshow\",\n          \"user\": {\n            \"id\": 11,\n            \"first_name\": \"Roger\",\n            \"last_name\": \"LAPIN\",\n          }\n        },\n        {\n          \"id\": 7,\n          \"status\": \"excused\",\n          \"user\": {\n            \"id\": 12,\n            \"first_name\": \"Marie\",\n            \"last_name\": \"DUPONT\",\n          }\n        },\n      ],\n      \"users_count\": 2,\n    }\n  ],\n}\n```\n"
  },
  "components": {
    "securitySchemes": {
      "access_token": {
        "type": "apiKey",
        "name": "access-token",
        "in": "header"
      },
      "uid": {
        "type": "apiKey",
        "name": "uid",
        "in": "header"
      },
      "client": {
        "type": "apiKey",
        "name": "client",
        "in": "header"
      }
    },
    "schemas": {
      "rdv": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "address": {
            "type": "string"
          },
          "agents": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/agent"
            }
          },
          "cancelled_at": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "collectif": {
            "type": "boolean"
          },
          "created_by": {
            "type": "string",
            "enum": [
              "agent",
              "user",
              "prescripteur"
            ]
          },
          "duration_in_min": {
            "type": "integer"
          },
          "lieu": {
            "$ref": "#/components/schemas/lieu",
            "nullable": true
          },
          "max_participants_count": {
            "type": "integer",
            "nullable": true
          },
          "motif": {
            "$ref": "#/components/schemas/motif"
          },
          "organisation": {
            "$ref": "#/components/schemas/organisation"
          },
          "starts_at": {
            "type": "string",
            "format": "date"
          },
          "status": {
            "type": "string",
            "enum": [
              "unknown",
              "seen",
              "excused",
              "revoked",
              "noshow"
            ]
          },
          "users": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/user"
            }
          },
          "users_count": {
            "type": "integer"
          },
          "uuid": {
            "type": "string"
          },
          "rdv_solidarites_rdv_id": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "starts_at",
          "duration_in_min",
          "cancelled_at",
          "address",
          "uuid",
          "created_by",
          "status",
          "users_count",
          "max_participants_count",
          "rdv_solidarites_rdv_id",
          "agents",
          "lieu",
          "motif",
          "users",
          "organisation"
        ]
      },
      "rdv_with_root": {
        "type": "object",
        "properties": {
          "rdv": {
            "$ref": "#/components/schemas/rdv"
          }
        },
        "required": [
          "rdv"
        ]
      },
      "agents": {
        "type": "object",
        "properties": {
          "agents": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/agent"
            }
          }
        },
        "required": [
          "agents"
        ]
      },
      "agent": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "email": {
            "type": "string"
          },
          "first_name": {
            "type": "string",
            "nullable": true
          },
          "last_name": {
            "type": "string",
            "nullable": true
          },
          "rdv_solidarites_agent_id": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "email",
          "first_name",
          "last_name",
          "rdv_solidarites_agent_id"
        ]
      },
      "user_with_root": {
        "type": "object",
        "properties": {
          "user": {
            "$ref": "#/components/schemas/user"
          }
        },
        "required": [
          "user"
        ]
      },
      "users": {
        "type": "object",
        "properties": {
          "users": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/user"
            }
          }
        },
        "required": [
          "users"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "address": {
            "type": "string",
            "nullable": true
          },
          "affiliation_number": {
            "type": "string",
            "nullable": true
          },
          "birth_date": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "birth_name": {
            "type": "string",
            "nullable": true
          },
          "created_at": {
            "type": "string",
            "format": "date"
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "phone_number": {
            "type": "string",
            "nullable": true
          },
          "department_internal_id": {
            "type": "string",
            "nullable": true
          },
          "rights_opening_date": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "enum": [
              "monsieur",
              "madame"
            ]
          },
          "uid": {
            "type": "string",
            "nullable": true
          },
          "role": {
            "type": "string",
            "nullable": true,
            "enum": [
              "demandeur",
              "conjoint"
            ]
          },
          "nir": {
            "type": "string",
            "nullable": true
          },
          "pole_emploi_id": {
            "type": "string",
            "nullable": true
          },
          "carnet_de_bord_carnet_id": {
            "type": "string",
            "nullable": true
          },
          "rdv_solidarites_user_id": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "uid",
          "affiliation_number",
          "role",
          "created_at",
          "department_internal_id",
          "first_name",
          "last_name",
          "title",
          "address",
          "phone_number",
          "email",
          "birth_date",
          "rights_opening_date",
          "birth_name",
          "rdv_solidarites_user_id",
          "nir",
          "pole_emploi_id",
          "carnet_de_bord_carnet_id"
        ]
      },
      "organisation_with_root": {
        "type": "object",
        "properties": {
          "organisation": {
            "$ref": "#/components/schemas/organisation"
          }
        },
        "required": [
          "organisation"
        ]
      },
      "organisations": {
        "type": "object",
        "properties": {
          "organisations": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/organisation"
            }
          }
        },
        "required": [
          "organisations"
        ]
      },
      "organisation": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string"
          },
          "phone_number": {
            "type": "string"
          },
          "department_number": {
            "type": "string"
          },
          "rdv_solidarites_organisation_id": {
            "type": "integer"
          },
          "motif_categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/motif_category"
            }
          }
        },
        "required": [
          "id",
          "name",
          "email",
          "phone_number",
          "department_number",
          "rdv_solidarites_organisation_id",
          "motif_categories"
        ]
      },
      "invitations": {
        "type": "object",
        "properties": {
          "invitations": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/invitation"
            }
          }
        },
        "required": [
          "invitations"
        ]
      },
      "invitation": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "format": {
            "type": "string",
            "enum": [
              "sms",
              "postal",
              "email"
            ]
          },
          "sent_at": {
            "type": "string"
          },
          "clicked": {
            "type": "boolean"
          },
          "rdv_with_referents": {
            "type": "boolean"
          },
          "motif_category": {
            "$ref": "#/components/schemas/motif_category"
          }
        },
        "required": [
          "id",
          "format",
          "sent_at",
          "clicked",
          "rdv_with_referents",
          "motif_category"
        ]
      },
      "lieu": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "phone_number": {
            "type": "string",
            "nullable": true
          },
          "rdv_solidarites_lieu_id": {
            "type": "integer"
          }
        },
        "required": [
          "address",
          "name",
          "phone_number",
          "rdv_solidarites_lieu_id"
        ]
      },
      "motifs": {
        "type": "object",
        "properties": {
          "motifs": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/motif"
            }
          }
        },
        "required": [
          "motifs"
        ]
      },
      "motif": {
        "type": "object",
        "properties": {
          "rdv_solidarites_motif_id": {
            "type": "integer"
          },
          "location_type": {
            "type": "string",
            "enum": [
              "public_office",
              "phone",
              "home"
            ]
          },
          "name": {
            "type": "string"
          },
          "motif_category": {
            "$ref": "#/components/schemas/motif_category"
          },
          "collectif": {
            "type": "boolean"
          },
          "follow_up": {
            "type": "boolean"
          }
        },
        "required": [
          "rdv_solidarites_motif_id",
          "name",
          "collectif",
          "location_type",
          "follow_up",
          "motif_category"
        ]
      },
      "motif_category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "short_name": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name",
          "short_name"
        ]
      },
      "department": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "number": {
            "type": "string"
          },
          "capital": {
            "type": "string"
          },
          "region": {
            "type": "string"
          },
          "organisations": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/organisation",
              "lieux": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/lieu"
                }
              },
              "motifs": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/motif"
                }
              }
            }
          }
        },
        "required": [
          "id",
          "number",
          "capital",
          "region",
          "organisations"
        ]
      },
      "department_with_root": {
        "type": "object",
        "properties": {
          "department": {
            "$ref": "#/components/schemas/department"
          }
        },
        "required": [
          "department"
        ]
      },
      "success_response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          }
        }
      },
      "error_unprocessable_entity": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "error_details": {
                  "type": "string"
                }
              },
              "required": [
                "error_details"
              ]
            }
          },
          "required": [
            "errors"
          ]
        }
      },
      "error_authentication": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "errors"
        ]
      },
      "error_forbidden": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "errors"
        ]
      },
      "error_not_found": {
        "type": "object",
        "properties": {
          "not_found": {
            "type": "string"
          }
        },
        "required": [
          "not_found"
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Invitation",
      "description": "Désigne une invitation à prendre rdv.\n             Elle est liée à un·e usager·ère, a un format (sms, mail ou postal), une catégorie de motif.\n             Elle est unique."
    },
    {
      "name": "User",
      "description": "Désigne le compte unique d'un·e usager·ère.\n            Il contient les informations de l'état civil ainsi que des informations\n            communes comme le NIR, l'ID interne au département."
    },
    {
      "name": "Agent",
      "description": "Désigne un·e agent·e. Un·e agent·e est lié·e à une ou plusieurs organisations."
    },
    {
      "name": "RDV",
      "description": "Désigne un rendez-vous.\n            Il contient des informations sur le rendez-vous lui-même, le ou les agent·es,\n            le ou les usager·ères, le lieu, le motif, l'organisation."
    },
    {
      "name": "Motif",
      "description": "Désigne le motif d'un rendez-vous.\n            Il contient des informations telles que le nom du motif, s'il est téléphonique,\n            sur place ou à domicile, ainsi que des détails annexes (collectif ou non, catégorie)."
    },
    {
      "name": "Organisation",
      "description": "Désigne une organisation. Une organisation contient des agent·es."
    }
  ],
  "servers": [
    {
      "url": "http://localhost:8000/",
      "description": "Serveur de développement"
    },
    {
      "url": "https://www.rdv-insertion-demo.fr",
      "description": "Serveur de démo"
    },
    {
      "url": "https://www.rdv-insertion.fr",
      "description": "Serveur de production"
    }
  ],
  "paths": {
    "api/v1/departments/{number}": {
      "get": {
        "summary": "Retrieves a department",
        "tags": [
          "Rdv"
        ],
        "description": "Renvoie les organisations, lieux et motifs du département",
        "parameters": [
          {
            "name": "number",
            "in": "path",
            "description": "Le numéro de département",
            "example": "13",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "access-token",
            "in": "header",
            "description": "Token d'accès (authentification)",
            "example": "SFYBngO55ImjD1HOcv-ivQ",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "client",
            "in": "header",
            "description": "Clé client d'accès (authentification)",
            "example": "Z6EihQAY9NWsZByfZ47i_Q",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "uid",
            "in": "header",
            "description": "Identifiant d'accès (authentification)",
            "example": "martine@demo.rdv-solidarites.fr",
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "access_token": [

            ],
            "uid": [

            ],
            "client": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "succès",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "department": {
                        "id": 7198,
                        "number": "13",
                        "capital": "Marseille",
                        "region": "Provence-Alpes-Côte d'Azur",
                        "organisations": [
                          {
                            "id": 6260,
                            "name": "Departement n°1",
                            "email": "organisation1@rdv-insertion.fr",
                            "phone_number": "0101010101",
                            "department_number": "13",
                            "rdv_solidarites_organisation_id": 1,
                            "motif_categories": [

                            ],
                            "motifs": [
                              {
                                "rdv_solidarites_motif_id": 1,
                                "name": "RSA orientation sur site",
                                "collectif": false,
                                "location_type": "public_office",
                                "follow_up": false,
                                "motif_category": {
                                  "id": 17161,
                                  "short_name": "rsa_orientation_1",
                                  "name": "RSA orientation"
                                }
                              }
                            ],
                            "lieux": [
                              {
                                "rdv_solidarites_lieu_id": 1,
                                "name": "DINUM",
                                "address": "20 avenue de Ségur 75007 Paris",
                                "phone_number": null
                              }
                            ]
                          }
                        ]
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/department_with_root"
                }
              }
            }
          },
          "403": {
            "description": "Renvoie 'forbidden' quand ",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Votre compte ne vous permet pas d'effectuer cette action"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_forbidden"
                }
              }
            }
          },
          "401": {
            "description": "Renvoie 'unauthorized' quand l'authentification est impossible",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Les identifiants de session RDV-Solidarités sont invalides"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_authentication"
                }
              }
            }
          },
          "404": {
            "description": "Renvoie 'not_found' quand le rdv n'existe pas",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "not_found": "Department"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_not_found"
                }
              }
            }
          }
        }
      }
    },
    "api/v1/rdvs/{uuid}": {
      "get": {
        "summary": "Retrieves a rdv",
        "tags": [
          "Rdv"
        ],
        "description": "Renvoie les détails du rdv",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "description": "L'uuid d'un rdv",
            "example": "c5097fb5-4f79-4ef4-b723-f295d888fd98",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "access-token",
            "in": "header",
            "description": "Token d'accès (authentification)",
            "example": "SFYBngO55ImjD1HOcv-ivQ",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "client",
            "in": "header",
            "description": "Clé client d'accès (authentification)",
            "example": "Z6EihQAY9NWsZByfZ47i_Q",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "uid",
            "in": "header",
            "description": "Identifiant d'accès (authentification)",
            "example": "martine@demo.rdv-solidarites.fr",
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "access_token": [

            ],
            "uid": [

            ],
            "client": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "Renvoie le rdv",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "rdv": {
                        "id": 942,
                        "starts_at": "2023-10-23T01:12:47.568+02:00",
                        "duration_in_min": 30,
                        "cancelled_at": null,
                        "address": "2O avenue de Ségur, 75007 Paris",
                        "uuid": "63866a6f-34a5-4a2b-a511-f27f6d67d62b",
                        "created_by": "user",
                        "status": "unknown",
                        "users_count": 0,
                        "max_participants_count": null,
                        "rdv_solidarites_rdv_id": 2,
                        "agents": [
                          {
                            "id": 1825,
                            "email": "agent7@gouv.fr",
                            "first_name": "jane7",
                            "last_name": "doe7",
                            "rdv_solidarites_agent_id": 7
                          }
                        ],
                        "lieu": {
                          "rdv_solidarites_lieu_id": 6,
                          "name": "DINUM",
                          "address": "20 avenue de Ségur 75007 Paris",
                          "phone_number": null
                        },
                        "motif": {
                          "rdv_solidarites_motif_id": 6,
                          "name": "RSA orientation sur site",
                          "collectif": false,
                          "location_type": "public_office",
                          "follow_up": false,
                          "motif_category": {
                            "id": 17167,
                            "short_name": "rsa_orientation_7",
                            "name": "RSA orientation"
                          }
                        },
                        "users": [
                          {
                            "id": 6259,
                            "uid": "bnVtZXJvXzMgLSBjb25qb2ludA==",
                            "affiliation_number": "numero_3",
                            "role": "conjoint",
                            "created_at": "0024-12-02T22:22:00.000+00:09",
                            "department_internal_id": "4061",
                            "first_name": "john3",
                            "last_name": "doe3",
                            "title": "monsieur",
                            "address": "27 avenue de Ségur 75007 Paris",
                            "phone_number": "+33782605941",
                            "email": "johndoe3@yahoo.fr",
                            "birth_date": null,
                            "rights_opening_date": null,
                            "birth_name": null,
                            "rdv_solidarites_user_id": 3,
                            "nir": null,
                            "pole_emploi_id": null,
                            "carnet_de_bord_carnet_id": null
                          }
                        ],
                        "organisation": {
                          "id": 6267,
                          "name": "Departement n°8",
                          "email": "organisation8@rdv-insertion.fr",
                          "phone_number": "0101010101",
                          "department_number": "4",
                          "rdv_solidarites_organisation_id": 8,
                          "motif_categories": [

                          ]
                        }
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/rdv_with_root"
                }
              }
            }
          },
          "403": {
            "description": "Renvoie 'forbidden' quand ",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Votre compte ne vous permet pas d'effectuer cette action"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_forbidden"
                }
              }
            }
          },
          "401": {
            "description": "Renvoie 'unauthorized' quand l'authentification est impossible",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Les identifiants de session RDV-Solidarités sont invalides"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_authentication"
                }
              }
            }
          },
          "404": {
            "description": "Renvoie 'not_found' quand le rdv n'existe pas",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "not_found": "Rdv"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_not_found"
                }
              }
            }
          }
        }
      }
    },
    "api/v1/organisations/{rdv_solidarites_organisation_id}/users/create_and_invite_many": {
      "post": {
        "summary": "create and invite users",
        "tags": [
          "Users"
        ],
        "description": "Créé et invite une liste d'usagers à prendre rdv.\n      La création et l'invitation se font de manière asynchrone.",
        "parameters": [
          {
            "name": "rdv_solidarites_organisation_id",
            "in": "path",
            "description": "L'id rdv-solidarites d'une organisation",
            "example": "403023",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "access-token",
            "in": "header",
            "description": "Token d'accès (authentification)",
            "example": "SFYBngO55ImjD1HOcv-ivQ",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "client",
            "in": "header",
            "description": "Clé client d'accès (authentification)",
            "example": "Z6EihQAY9NWsZByfZ47i_Q",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "uid",
            "in": "header",
            "description": "Identifiant d'accès (authentification)",
            "example": "martine@demo.rdv-solidarites.fr",
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "access_token": [

            ],
            "uid": [

            ],
            "client": [

            ]
          }
        ],
        "request_examples": [
          {
            "value": {
              "users": [
                {
                  "first_name": "Didier",
                  "last_name": "Drogba",
                  "title": "monsieur",
                  "affiliation_number": "10492390",
                  "role": "demandeur",
                  "email": "didier@drogba.com",
                  "phone_number": "0782605941",
                  "birth_date": "11/03/1978",
                  "address": "13 rue de la République 13001 MARSEILLE",
                  "department_internal_id": "11111444",
                  "nir": "180768374859404"
                },
                {
                  "first_name": "Dimitri",
                  "last_name": "Payet",
                  "title": "monsieur",
                  "affiliation_number": "0782605941",
                  "role": "conjoint",
                  "email": "amine.dhobb+testapi2@gmail.com",
                  "phone_number": "0782605941",
                  "birth_date": "29/03/1987",
                  "rights_opening_date": "15/11/2021",
                  "address": "5 Avenue du Moulin des Baux, 13260 Cassis",
                  "department_internal_id": "22221111",
                  "pole_emploi_id": "22233333",
                  "nir": "180428848848853",
                  "invitation": {
                    "motif_category": {
                      "name": "RSA orientation"
                    }
                  }
                }
              ]
            },
            "name": "request_example_1",
            "summary": "A request example"
          }
        ],
        "responses": {
          "200": {
            "description": "succès",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "success": true
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/success_response"
                }
              }
            }
          },
          "403": {
            "description": "Renvoie 'forbidden' quand ",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Votre compte ne vous permet pas d'effectuer cette action"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_forbidden"
                }
              }
            }
          },
          "401": {
            "description": "Renvoie 'unauthorized' quand l'authentification est impossible",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Les identifiants de session RDV-Solidarités sont invalides"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_authentication"
                }
              }
            }
          },
          "404": {
            "description": "Renvoie 'not_found' quand le rdv n'existe pas",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "not_found": "Organisation"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_not_found"
                }
              }
            }
          },
          "422": {
            "description": "Renvoie 'unprocessable_entity' quand quand + de 25 usagers sont envoyés",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "success": false,
                      "errors": [
                        {
                          "error_details": "Les usagers doivent être envoyés par lots de 25 maximum"
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_unprocessable_entity"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "users": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/user",
                      "invitation": {
                        "type": "object",
                        "nullable": true,
                        "properties": {
                          "rdv_solidarites_lieu_id": {
                            "type": "string",
                            "nullable": true
                          },
                          "motif_category": {
                            "type": "object",
                            "nullable": true,
                            "properties": {
                              "name": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "required": [
                    "users"
                  ]
                }
              }
            }
          },
          "required": true
        }
      }
    },
    "api/v1/organisations/{rdv_solidarites_organisation_id}/users/create_and_invite": {
      "parameters": [
        {
          "name": "rdv_solidarites_organisation_id",
          "in": "path",
          "description": "L'id rdv-solidarites d'une organisation",
          "example": "403023",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "post": {
        "summary": "create and invite user",
        "tags": [
          "User"
        ],
        "description": "Créé et invite une liste d'usagers à prendre rdv.\n      La création et l'invitation se font de manière synchrone.",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "Token d'accès (authentification)",
            "example": "SFYBngO55ImjD1HOcv-ivQ",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "client",
            "in": "header",
            "description": "Clé client d'accès (authentification)",
            "example": "Z6EihQAY9NWsZByfZ47i_Q",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "uid",
            "in": "header",
            "description": "Identifiant d'accès (authentification)",
            "example": "martine@demo.rdv-solidarites.fr",
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "access_token": [

            ],
            "uid": [

            ],
            "client": [

            ]
          }
        ],
        "request_examples": [
          {
            "value": {
              "user": {
                "first_name": "Didier",
                "last_name": "Drogba",
                "title": "monsieur",
                "affiliation_number": "10492390",
                "role": "demandeur",
                "email": "didier@drogba.com",
                "phone_number": "0782605941",
                "birth_date": "11/03/1978",
                "address": "13 rue de la République 13001 MARSEILLE",
                "department_internal_id": "11111444",
                "nir": "180212929958197",
                "invitation": {
                  "motif_category": {
                    "name": "RSA orientation"
                  }
                }
              }
            },
            "name": "request_example_1",
            "summary": "A request example"
          }
        ],
        "responses": {
          "200": {
            "description": "succès",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "success": true,
                      "user": {
                        "id": 6267,
                        "uid": "MTA0OTIzOTAgLSBkZW1hbmRldXI=",
                        "affiliation_number": "10492390",
                        "role": "demandeur",
                        "created_at": "0024-12-02T22:22:00.000+00:09",
                        "department_internal_id": "11111444",
                        "first_name": "Didier",
                        "last_name": "Drogba",
                        "title": "monsieur",
                        "address": "13 rue de la République 13001 MARSEILLE",
                        "phone_number": "+33782605941",
                        "email": "didier@drogba.com",
                        "birth_date": "1978-03-11",
                        "rights_opening_date": null,
                        "birth_name": null,
                        "rdv_solidarites_user_id": 11,
                        "nir": "180212929958197",
                        "pole_emploi_id": null,
                        "carnet_de_bord_carnet_id": null
                      },
                      "invitations": [
                        {
                          "id": 1354,
                          "format": "sms",
                          "sent_at": "2023-10-20T01:12:48.721+02:00",
                          "clicked": false,
                          "rdv_with_referents": false,
                          "motif_category": {
                            "id": 17176,
                            "short_name": "rsa_orientation_16",
                            "name": "RSA orientation"
                          }
                        },
                        {
                          "id": 1354,
                          "format": "sms",
                          "sent_at": "2023-10-20T01:12:48.721+02:00",
                          "clicked": false,
                          "rdv_with_referents": false,
                          "motif_category": {
                            "id": 17176,
                            "short_name": "rsa_orientation_16",
                            "name": "RSA orientation"
                          }
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "$ref": "#/components/schemas/user",
                    "invitations": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/invitation",
                        "motif_category": {
                          "$ref": "#/components/schemas/invitation"
                        }
                      }
                    }
                  },
                  "required": [
                    "success",
                    "user",
                    "invitations"
                  ]
                }
              }
            }
          },
          "403": {
            "description": "Renvoie 'forbidden' quand ",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Votre compte ne vous permet pas d'effectuer cette action"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_forbidden"
                }
              }
            }
          },
          "401": {
            "description": "Renvoie 'unauthorized' quand l'authentification est impossible",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "errors": [
                        "Les identifiants de session RDV-Solidarités sont invalides"
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_authentication"
                }
              }
            }
          },
          "404": {
            "description": "Renvoie 'not_found' quand le rdv n'existe pas",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "not_found": "Organisation"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_not_found"
                }
              }
            }
          },
          "422": {
            "description": "Renvoie 'unprocessable_entity' quand quand une invitation ne peut pas être envoyée",
            "content": {
              "application/json": {
                "examples": {
                  "test_example": {
                    "value": {
                      "success": false,
                      "errors": [
                        {
                          "error_details": "Erreur en envoyant l'invitation par sms: l'invitation par sms n'a pas pu être délivrée"
                        },
                        {
                          "error_details": "Erreur en envoyant l'invitation par email: l'invitation par sms n'a pas pu être délivrée"
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/error_unprocessable_entity"
                }
              }
            }
          }
        }
      }
    }
  }
}